# Generated by Django 5.2.12 on 2026-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='bpm',
            field=models.IntegerField(default=0, verbose_name='节奏BPM'),
        ),
        migrations.AddField(
            model_name='music',
            name='publisher',
            field=models.CharField(blank=True, max_length=128, verbose_name='发行公司'),
        ),
        migrations.AddField(
            model_name='rate',
            name='play_duration',
            field=models.IntegerField(default=0, verbose_name='播放时长(秒)'),
        ),
        migrations.AddField(
            model_name='rate',
            name='skip_count',
            field=models.IntegerField(default=0, verbose_name='跳过次数'),
        ),
        migrations.AddField(
            model_name='rate',
            name='total_duration',
            field=models.IntegerField(default=1, verbose_name='歌曲总时长(秒)'),
        ),
    ]
