# Generated by Django 5.2.12 on 2026-04-22 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('artist', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('years', models.CharField(max_length=128)),
                ('bpm', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('sump', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('pic', models.CharField(blank=True, max_length=256, null=True)),
                ('publisher', models.CharField(blank=True, max_length=128, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='user.tags')),
                ('collect', models.ManyToManyField(blank=True, related_name='collected_musics', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(verbose_name='评分')),
                ('play_duration', models.IntegerField(default=0, verbose_name='播放时长(秒)')),
                ('total_duration', models.IntegerField(default=1, verbose_name='歌曲总时长(秒)')),
                ('skip_count', models.IntegerField(default=0, verbose_name='跳过次数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
