# Generated by Django 5.2.12 on 2026-04-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
